---
# handlers file for zabbix_server
- name: restart service postgresql
  service:
    name: postgresql-{{ zabbix_server_postgresql_version }}
    state: restarted
    enabled: yes

- name: restart service zabbix-server
  service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: restart service php-fpm
  service:
    name: rh-php72-php-fpm
    state: restarted
    enabled: yes

- name: restart service nginx
  service:
    name: rh-nginx116-nginx
    state: restarted
    enabled: yes
